services:
  frontend:
    image: bazika-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    image: bazika-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4001:4001"

  nginx:
    image: bazika-ingress:latest
    build:
      context: nginx
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=test.bazika.com
      - APP_URL=http://frontend:3000
      - API_URL=http://backend:4001
    depends_on:
      - frontend
      - backend
    ports:
        - "80:80"
        - "443:443"
