services:
  frontend:
    image: bazika-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

  backend:
    image: bazika-backend:latest
    build:
        context: .
        dockerfile: apps/backend/Dockerfile
