name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build .env.local file
        working-directory: ./apps/frontend
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          envsubst < .env.envsubst > .env.local

      - name: Allow insecure Docker registry
        run: |
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries": ["213.109.237.185:5000"]}' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build, tag, and push images to self-hosted registry
        id: build-image
        env:
          REGISTRY: 213.109.237.185:5000
          IMAGE_TAG: latest
        run: |
          docker compose -f docker-compose.build.yml build frontend nginx

          docker tag bazika-frontend:latest $REGISTRY/bazika-frontend:$IMAGE_TAG
          docker tag bazika-ingress:latest $REGISTRY/bazika-ingress:$IMAGE_TAG

          docker push $REGISTRY/bazika-frontend:$IMAGE_TAG
          docker push $REGISTRY/bazika-ingress:$IMAGE_TAG
